### ISSUE TITLE
Does the voice call demo use the same model trained by this repo

### ISSUE THREAD

**Issue by viyjy** [fixie-ai/ultravox#123]
HI, thanks for your work. I have tried this [voice call](https://www.ai.town/characters/a90fcca3-53c0-4111-b30a-4984883a23ef) and found it can take streaming audio as the input if I am correct. 
I am wondering (1) if the voice call demo use the same model trained by this repo? (2) how do you implement the voice call demo.
Thanks very much!

**Comment by zkoch** [comment]
@viyjy yes, it uses the same model. You can do the same thing using our apis: docs.ultravox.ai
