### ISSUE TITLE
Voice cloning

### ISSUE THREAD

**Issue by platform-kit** [fixie-ai/ultravox#124]
Does this model support zero-shot voice cloning? Or voice cloning via finetune?

**Comment by zkoch** [comment]
@platform-kit Yes, you can do it via our APIs (docs.ultravox.ai)

**Comment by platform-kit** [comment]
@zkoch very cool - though, it's unclear -- is the voice cloning functionality part of the OSS offering of UltraVox or is it using a 3rd party API? Can I do this locally?

**Comment by zkoch** [comment]
Ah, sorry. Not part of the base model yet. We're still working on speech output side of the model.
