### ISSUE TITLE
TTS in the demo 

### ISSUE THREAD

**Issue by poupinel** [fixie-ai/ultravox#152]
Hi! Thanks for the great work on ultrabox! I really enjoyed the demo and your blog post on the roadmap. If I understood correctly, current demo relies on an external TTS. May I ask what TTS did you use?

**Comment by sachin7695** [comment]
@poupinel can you share the link to the blogpost? Thank you :)

**Comment by zkoch** [comment]
@poupinel We use a couple of different ones, but the default voice for the demo is currently through ElevenLabs

@sachin7695 The blog post is here: https://www.ultravox.ai/blog/ultravox-an-open-weight-alternative-to-gpt-4o-realtime
