### ISSUE TITLE
alternatives to whisper for history Integration in speechLLM

### ISSUE THREAD

**Issue by atulyaatul1999** [fixie-ai/ultravox#162]
I noticed that Whisper is being used for transcription on HF space and wanted to explore alternative approaches for incorporating history without relying on Whisper for transcription. The primary goal of SpeechLLM was to eliminate the dependency on ASR, but it seems ASR is still part of the process. I would like to understand more about this and explore if there are different methods to achieve the intended functionality.

**Comment by zkoch** [comment]
Ultravox itself does not rely on ASR, but it does use Whisper's encoder. Anywhere you see ASR is usually for the user's benefit, not for Ultravox's benefit.
