### ISSUE TITLE
running it on mac

### ISSUE THREAD

**Issue by milsun** [fixie-ai/ultravox#88]
how can i run it on my mac m2, llama.cpp doesnt support this as yet?

**Comment by zqhuang211** [comment]
Currently, training and inference work on Apple Silicon (`cpu` or `mps`), though it’s significantly slower compared to Nvidia GPUs.

If you’d like to try out the Gradio demo on a Mac, simply run `just gradio`. By default, this will use `mps` for inference.

**Comment by zqhuang211** [comment]
Ultravox doesn’t support `llama.cpp` yet. We plan to explore this in the future and definitely welcome contributions from the community.

**Comment by milsun** [comment]
running it with "mps" would be fp32 I guess, so would need a ton of RAM, right?

**Comment by zqhuang211** [comment]
Yes for `float32`. You can also set `--data_type=float16`, which reduces RAM usage to around 20GB. We haven’t tried quantization yet.

**Comment by juberti** [comment]
Fixed in #95
