### ISSUE TITLE
 Implement model quantization to reduce memory usage during inference

### ISSUE THREAD

**Issue by zqhuang211** [fixie-ai/ultravox#94]
When running the gradio demo (`just gradio`), the model currently requires approximately 32GB of memory to load and perform inference. While this can be reduced to around 20GB with the --data_type float16 option, implementing 8-bit, 6-bit, or 4-bit quantization could further reduce the memory requirements.

**Comment by juberti** [comment]
See #8 for details of our existing work on this. I'll take another look at it now though.
